# frozen_string_literal: true

require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe('/medication_transactions', type: :request) do
  # This should return the minimal set of attributes required to create a valid
  # MedicationTransaction. As you add validations to MedicationTransaction, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    skip('Add a hash of attributes valid for your model')
  end

  let(:invalid_attributes) do
    skip('Add a hash of attributes invalid for your model')
  end

  describe 'GET /index' do
    it 'renders a successful response' do
      MedicationTransaction.create!(valid_attributes)
      get medication_transactions_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /show' do
    it 'renders a successful response' do
      medication_transaction = MedicationTransaction.create!(valid_attributes)
      get medication_transaction_url(medication_transaction)
      expect(response).to(be_successful)
    end
  end

  describe 'GET /new' do
    it 'renders a successful response' do
      get new_medication_transaction_url
      expect(response).to(be_successful)
    end
  end

  describe 'GET /edit' do
    it 'renders a successful response' do
      medication_transaction = MedicationTransaction.create!(valid_attributes)
      get edit_medication_transaction_url(medication_transaction)
      expect(response).to(be_successful)
    end
  end

  describe 'POST /create' do
    context 'with valid parameters' do
      it 'creates a new MedicationTransaction' do
        expect do
          post(medication_transactions_url, params: { medication_transaction: valid_attributes })
        end.to(change(MedicationTransaction, :count).by(1))
      end

      it 'redirects to the created medication_transaction' do
        post medication_transactions_url, params: { medication_transaction: valid_attributes }
        expect(response).to(redirect_to(medication_transaction_url(MedicationTransaction.last)))
      end
    end

    context 'with invalid parameters' do
      it 'does not create a new MedicationTransaction' do
        expect do
          post(medication_transactions_url, params: { medication_transaction: invalid_attributes })
        end.to(change(MedicationTransaction, :count).by(0))
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post medication_transactions_url, params: { medication_transaction: invalid_attributes }
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe 'PATCH /update' do
    context 'with valid parameters' do
      let(:new_attributes) do
        skip('Add a hash of attributes valid for your model')
      end

      it 'updates the requested medication_transaction' do
        medication_transaction = MedicationTransaction.create!(valid_attributes)
        patch medication_transaction_url(medication_transaction), params: { medication_transaction: new_attributes }
        medication_transaction.reload
        skip('Add assertions for updated state')
      end

      it 'redirects to the medication_transaction' do
        medication_transaction = MedicationTransaction.create!(valid_attributes)
        patch medication_transaction_url(medication_transaction), params: { medication_transaction: new_attributes }
        medication_transaction.reload
        expect(response).to(redirect_to(medication_transaction_url(medication_transaction)))
      end
    end

    context 'with invalid parameters' do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        medication_transaction = MedicationTransaction.create!(valid_attributes)
        patch medication_transaction_url(medication_transaction), params: { medication_transaction: invalid_attributes }
        expect(response).to(have_http_status(:unprocessable_entity))
      end
    end
  end

  describe 'DELETE /destroy' do
    it 'destroys the requested medication_transaction' do
      medication_transaction = MedicationTransaction.create!(valid_attributes)
      expect do
        delete(medication_transaction_url(medication_transaction))
      end.to(change(MedicationTransaction, :count).by(-1))
    end

    it 'redirects to the medication_transactions list' do
      medication_transaction = MedicationTransaction.create!(valid_attributes)
      delete medication_transaction_url(medication_transaction)
      expect(response).to(redirect_to(medication_transactions_url))
    end
  end
end
